version: "3"
services:
  redis:
    image: redis:5.0-alpine
    ports:
       - '6379:6379'
    volumes:
      - /tmp/db:/var/lib/redis/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: './entrypoint.sh'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.6
    ports:
       - "5432:5432"
    volumes:
       - ./tmp/db:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: rails
       POSTGRES_PASSWORD: hunter2
