default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] ||= 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] ||= '5432' %>
  username: <%= ENV['DATABASE_USER'] ||= 'rails' %>
  password: <%= ENV['DATABASE_PASSWORD'] ||= 'hunter2' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: amplicon_development

test:
  <<: *default
  database: amplicon_test
